export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const GET_PATIENTS = "GET_PATIENTS";
export const PATIENT_ADDED = "PATIENT_ADDED";

export const GET_RECEPTIONISTS = "GET_RECEPTIONISTS";
export const RECEPTIONIST_ADDED = "RECEPTIONIST_ADDED";

export const GET_DOCTORS = "GET_DOCTORS";
export const DOCTOR_ADDED = "DOCTOR_ADDED";

export const GET_PLAN = "GET_PLAN";
export const GET_PLAN_FOR_EDITION = "GET_PLAN_FOR_EDITION";
export const ADD_TO_MEAL_PLAN = "ADD_TO_MEAL_PLAN";
export const REMOVE_FROM_MEAL_PLAN = "REMOVE_FROM_MEAL_PLAN";
export const CHANGE_MEAL_PLAN_NAME = "CHANGE_MEAL_PLAN_NAME";